openapi: "3.1.0"    
info:
  title: Stratologia API
  version: "0.1.0"

servers:
  - url: http://localhost:8000
    description: Local dev server

paths:
  /citizens/{id}:
    get:
      summary: Get my profile
  /applications:
    post:
      summary: Submit a new deferment/enlistment request
  /applications/{id}/approve:
    post:
      summary: Officer approves an application
